@host = http://localhost
@port = 3000
@restHost = {{host}}:{{port}}

@apiKey = AIzaSyANjmFgFg8RWsY4Ndxl49HXQbEfAwpoyQk

@keyword = ขาหมู
@place = บางกะปิ

#GET ร้านข้าวขาหมู near บางกะปิ
GET {{restHost}}/restaurant?keyword={{keyword}}&place={{place}}